---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-data-gather
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-data-gather
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - update
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - deployment/finalizers
    verbs:
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-data-gather
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-data-gather
subjects:
  - kind: ServiceAccount
    name: aws-data-gather
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-data-gather
rules:
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    resourceNames:
    - hostnetwork
    verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-data-gather
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-data-gather
subjects:
- kind: ServiceAccount
  name: aws-data-gather
