apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ocs-osd-deployer.clusterserviceversion.yaml
commonAnnotations:
  olm.skipRange: '>=0.0.1 <2.0.3'
patches:
- patch: '[{"op": "replace", "path": "/spec/replaces", "value": "2.0.2"}]'
  target:
    kind: ClusterServiceVersion
    name: ocs-osd-deployer.v0.0.0
