---
name: image-builder

on:
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go environment
        uses: red-hat-storage/ocs-osd-deployer@main
      - name: Build operator docker image
        run: make docker-build
