---
name: golangci-lint

on:
  pull_request:
    branches: 
    - '*'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go environment
        uses: red-hat-storage/ocs-osd-deployer@main
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: --timeout 3m --verbose
